### ISSUE TITLE
[BUG] Packet handling error

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#12]
` [Client thread/ERROR] FIXME: Packet handling error
[19/03/2024 15:33:35 下午] 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
[19/03/2024 15:33:35 下午] 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
[19/03/2024 15:33:35 下午] 	at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864)
[19/03/2024 15:33:35 下午] 	at net.minecraft.network.PacketBuffer.readCompoundTag(PacketBuffer.java:303)
[19/03/2024 15:33:35 下午] 	at net.minecraftforge.fml.common.network.ByteBufUtils.readTag(ByteBufUtils.java:227)
[19/03/2024 15:33:35 下午] 	at mekanism.common.PacketHandler.readNBT(PacketHandler.java:140)
[19/03/2024 15:33:35 下午] 	at mekanism.common.util.TileUtils.readTankData(TileUtils.java:54)
[19/03/2024 15:33:35 下午] 	at mekanism.common.tile.TileEntityFactory.handlePacketData(TileEntityFactory.java:1017)
[19/03/2024 15:33:35 下午] 	at mekanism.common.network.PacketTileEntity.lambda$onMessage$0(PacketTileEntity.java:34)
[19/03/2024 15:33:35 下午] 	at mekanism.common.network.PacketTileEntity$$Lambda$4983/2081371296.run(Unknown Source)
[19/03/2024 15:33:35 下午] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19/03/2024 15:33:35 下午] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19/03/2024 15:33:35 下午] 	at net.minecraft.util.Util.runTask(Util.java:529)
[19/03/2024 15:33:35 下午] 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
[19/03/2024 15:33:35 下午] 	at net.minecraft.client.Minecraft.run(Minecraft.java:3614)
[19/03/2024 15:33:35 下午] 	at net.minecraft.client.main.Main.main(SourceFile:123)
[19/03/2024 15:33:35 下午] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19/03/2024 15:33:35 下午] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19/03/2024 15:33:35 下午] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19/03/2024 15:33:35 下午] 	at java.lang.reflect.Method.invoke(Method.java:497)
[19/03/2024 15:33:35 下午] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19/03/2024 15:33:35 下午] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by sddsd2332** [comment]
之前的mek版本是哪里的？
如果是v10 重新打掉工厂后放置

**Comment by zeng-github01** [comment]
> 之前的mek版本是哪里的？
> 如果是v10 重新打掉工厂后放置

之前已经打过一次了，难道有漏网之鱼？
