### ISSUE TITLE
气体自动输出导致崩溃

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#32]
应该是最近一次的输入输出合并造成的

 [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
        at mekanism.common.tile.component.TileComponentEjector.eject2(TileComponentEjector.java:136) ~[TileComponentEjector.class:?]
        at mekanism.common.tile.component.TileComponentEjector.tick(TileComponentEjector.java:91) ~[TileComponentEjector.class:?]
        at mekanism.common.tile.prefab.TileEntityBasicBlock.doRestrictedTick(TileEntityBasicBlock.java:82) ~[TileEntityBasicBlock.class:?]
        at mekanism.common.tile.base.TileEntityRestrictedTick.update(TileEntityRestrictedTick.java:21) ~[TileEntityRestrictedTick.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1838) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more

@sddsd2332

**Comment by sddsd2332** [comment]
什么机器？发崩溃日志要发完整，不然不知道是什么机器出问题

**Comment by zeng-github01** [comment]
离心机，做裂变燃料的那个

**Comment by zeng-github01** [comment]
> 什么机器？发崩溃日志要发完整，不然不知道是什么机器出问题
> 

同位素离心机，做裂变燃料的那个。开自动输出就崩。在气体输出合并之前没有问题

**Comment by zeng-github01** [comment]
[crash-2024-05-23_18.02.58-server.txt](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/files/15419582/crash-2024-05-23_18.02.58-server.txt)


@sddsd2332 相关日志

感觉我这专业开发测试员，崩了三回了XD

**Comment by sddsd2332** [comment]
少写一段导致的，修了
