### ISSUE TITLE
Can not use Groovy Script

### ISSUE THREAD

**Issue by sekinon-maru9** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#86]
I use DeepL translation as I'm not English native.

I get an error when I try to add a recipe for PRC in MekCEu(Mekanism-CE-Unofficial-All-9.9.1.214.jar).
I use example PRC recipe.
(GroovyScript − 1.1.3)
https://cleanroommc.com/groovy-script/mods/mekanism/pressurized_reaction_chamber

error log

> An exception occurred while running scripts. Look at latest.log for a full stacktrace:
> 	groovy.lang.MissingPropertyException: No such property: pressurized_reaction_chamber for class: mekanism.common.integration.groovyscript.MekanismAdd
Possible solutions: pressurizedReactionChamber
> 		at postInit.test_mekCEu.run(test_mekCEu.groovy:1)
> 		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.runScript(GroovySandbox.java:167)
> 		at com.cleanroommc.groovyscript.sandbox.GroovyScriptSandbox.runScript(GroovyScriptSandbox.java:181)
> 		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.loadScripts(GroovySandbox.java:140)

Remarks.
https://github.com/CleanroomMC/GroovyScript/issues/247#issuecomment-2392674272

**Comment by sddsd2332** [comment]
It's not clear exactly how the problem happened
Mekceu is just an extension of MEK within GRS
Not sure how this happened.
This can be solved by modifying the other identifiers
